### ISSUE TITLE
Could not resolve com.chrynan.parcelable:parcelable-core:0.5.0.

### ISSUE THREAD

**Issue by radimjanda754** [chRyNaN/serialization-parcelable#11]
Hello, our automated builds sometimes start crashing because of this error related to parcelable-core and configuration cache

```
FAILURE: Build failed with an exception.

* What went wrong:
Configuration cache state could not be cached: field `provider` of `org.gradle.configurationcache.serialization.codecs.ProviderBackedFileCollectionSpec` bean found in field `element` of `java.util.Collections$SingletonList` bean found in field `elements` of `org.gradle.configurationcache.serialization.codecs.ResolutionBackedFileCollectionSpec` bean found in field `__classpathSnapshot__` of `org.jetbrains.kotlin.gradle.tasks.KotlinCompile$ClasspathSnapshotProperties` bean found in field `__classpathSnapshotProperties__` of task `:shared:ktx:kaptGenerateStubsDebugKotlinAndroid` of type `org.jetbrains.kotlin.gradle.internal.KaptGenerateStubsTask`: error writing value of type 'org.gradle.api.internal.provider.DefaultProvider'
> Could not resolve all files for configuration ':shared:ktx:debugCompileClasspath'.
   > Could not resolve com.chrynan.parcelable:parcelable-core:0.5.0.
     Required by:
         project :shared:ktx
      > Skipped due to earlier error

* Exception is:
org.gradle.configurationcache.ConfigurationCacheError: Configuration cache state could not be cached: field `provider` of `org.gradle.configurationcache.serialization.codecs.ProviderBackedFileCollectionSpec` bean found in field `element` of `java.util.Collections$SingletonList` bean found in field `elements` of `org.gradle.configurationcache.serialization.codecs.ResolutionBackedFileCollectionSpec` bean found in field `__classpathSnapshot__` of `org.jetbrains.kotlin.gradle.tasks.KotlinCompile$ClasspathSnapshotProperties` bean found in field `__classpathSnapshotProperties__` of task `:shared:ktx:kaptGenerateStubsDebugKotlinAndroid` of type `org.jetbrains.kotlin.gradle.internal.KaptGenerateStubsTask`: error writing value of type 'org.gradle.api.internal.provider.DefaultProvider'
	at org.gradle.configurationcache.problems.ProblemsListener$DefaultImpls.onError(ProblemsListener.kt:37)
	at org.gradle.configurationcache.problems.ConfigurationCacheProblems.onError(ConfigurationCacheProblems.kt:38)
	at org.gradle.configurationcache.serialization.AbstractIsolateContext.onError(Contexts.kt:418)
	at org.gradle.configurationcache.serialization.beans.BeanPropertyWriterKt.writeNextProperty(BeanPropertyWriter.kt:100)
	at org.gradle.configurationcache.serialization.beans.BeanPropertyWriter.writeStateOf(BeanPropertyWriter.kt:53)
	at org.gradle.configurationcache.serialization.codecs.BeanCodec.writeBeanOf(BeanCodec.kt:59)
	at org.gradle.configurationcache.serialization.codecs.BeanCodec.encode(BeanCodec.kt:37)
	at org.gradle.configurationcache.serialization.CombinatorsKt$reentrant$1$encodeLoop$1.invokeSuspend(Combinators.kt:144)
        ...
```

Once it starts, the builds keep crashing for several hours, until it resolves without any action from us.

Any idea what causes this and how to prevent it?

**Comment by chrisjenx** [comment]
We have a similar issue now, gradle randomly stopped resolving the latest version (despite working for what.. a year+?)

**Comment by chrisjenx** [comment]
OK I found out the issue, repy has nginx incorrectly configured, they return 404 for HEAD requests
